### ISSUE TITLE
Second hand skips quickly through 59th second

### ISSUE THREAD

**Issue by derekantrican** [dotnet/android-samples#314]
Screen recording:

![](https://i.imgur.com/1833Nxn.gif)

Note how when the second hand ticks through the seconds, it ticks at a consistent speed until it hits the 59th second. At that point it skips quickly onto the 60/00 second.

This is with the code in the sample with no changes

#### What's the expected result?

All secondhand ticks should be consistent

**Comment by derekantrican** [comment]
@pjcollins were there changes made to fix this?

**Comment by pjcollins** [comment]
I've closed this as we've removed this sample from the gallery.

**Comment by mmitche** [comment]
This may be my favorite bug of all time.

**Comment by missymessa** [comment]
> This may be my favorite bug of all time.

I dunno, this is a strong contender, too. https://github.com/dotnet/try/issues/290

**Comment by mmitche** [comment]
> > This may be my favorite bug of all time.
> 
> I dunno, this is a strong contender, too. [dotnet/try#290](https://github.com/dotnet/try/issues/290)

This one is better.
